// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 项目数据配置
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

type ProjectType = "baseline" | "agent";

interface Project {
  name: string;
  path: string;
  description: string;
  type: ProjectType;
}

const PROJECTS: Project[] = [
  {
    name: "Claude Code",
    path: "/baseline/claude-code/",
    description: "Baseline implementation generated by Claude Code.",
    type: "baseline",
  },
  {
    name: "Gemini",
    path: "/baseline/gemini/",
    description: "Baseline implementation generated by Gemini.",
    type: "baseline",
  },
  {
    name: "Claude Sonnet 4.5",
    path: "/code-agent/claude-sonnet-4.5/",
    description: "Implementation by Code Agent using Claude Sonnet 4.5.",
    type: "agent",
  },
  {
    name: "Deepseek V3",
    path: "/code-agent/deepseek-v3/",
    description: "Implementation by Code Agent using Deepseek V3.",
    type: "agent",
  },
  {
    name: "Qwen3 Coder Plus",
    path: "/code-agent/qwen3-coder-plus/",
    description: "Implementation by Code Agent using Qwen3 Coder Plus.",
    type: "agent",
  },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 项目卡片组件
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

function ProjectCard({ project }: { project: Project }) {
  const isAgent = project.type === "agent";

  return (
    <a
      href={project.path}
      className="group block h-full p-6 md:p-8 bg-white rounded-2xl border border-gray-200 transition-all duration-200 hover:border-gray-400 hover:shadow-md"
    >
      <div className="flex items-center justify-between gap-3 mb-5">
        <h2 className="text-lg md:text-xl font-medium text-gray-900 group-hover:text-blue-600 transition-colors">
          {project.name}
        </h2>
        {isAgent && (
          <span className="px-3.5 py-2 text-sm font-semibold text-blue-600 bg-blue-50 rounded-lg whitespace-nowrap">
            AGENT
          </span>
        )}
      </div>
      <p className="text-sm md:text-base text-gray-600 leading-relaxed mb-5">
        {project.description}
      </p>
      <span className="text-xs md:text-sm text-gray-400 font-mono break-all">
        {project.path}
      </span>
    </a>
  );
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 分组展示组件
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

interface ProjectSectionProps {
  title: string;
  description: string;
  projects: Project[];
}

function ProjectSection({
  title,
  description,
  projects,
}: ProjectSectionProps) {
  return (
    <section className="mb-12 md:mb-20">
      <div className="mb-6 md:mb-8 pb-4 md:pb-5 border-b border-gray-300">
        <h2 className="text-sm md:text-base font-semibold uppercase tracking-wider text-gray-800 mb-2">
          {title}
        </h2>
        <p className="text-sm md:text-base text-gray-600">{description}</p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-5">
        {projects.map((project) => (
          <ProjectCard key={project.path} project={project} />
        ))}
      </div>
    </section>
  );
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 主页组件
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export default function Home() {
  const agentProjects = PROJECTS.filter((p) => p.type === "agent");
  const baselineProjects = PROJECTS.filter((p) => p.type === "baseline");

  return (
    <main className="min-h-screen bg-gray-50">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 md:px-8 py-12 md:py-20">
        <header className="mb-12 md:mb-20">
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-light text-gray-900 mb-4 md:mb-5 tracking-tight">
            COMP7103 Project Examples
          </h1>
          <p className="text-base md:text-lg text-gray-600 max-w-2xl leading-relaxed">
            A collection of arXiv CS Daily implementations demonstrating
            different development approaches.
          </p>
        </header>

        <ProjectSection
          title="Code Agent"
          description="Agent-driven implementations using different LLM backends"
          projects={agentProjects}
        />

        <ProjectSection
          title="Baseline"
          description="Traditional AI-assisted development implementations"
          projects={baselineProjects}
        />
      </div>
    </main>
  );
}
