// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 项目数据配置
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

type ProjectType = "baseline" | "agent";

interface Project {
  name: string;
  path: string;
  description: string;
  type: ProjectType;
}

const PROJECTS: Project[] = [
  {
    name: "Claude Code",
    path: "/baseline/claude-code/",
    description: "Baseline implementation generated by Claude Code.",
    type: "baseline",
  },
  {
    name: "Gemini",
    path: "/baseline/gemini/",
    description: "Baseline implementation generated by Gemini.",
    type: "baseline",
  },
  {
    name: "Claude Sonnet 4.5",
    path: "/code-agent/claude-sonnet-4.5/",
    description: "Implementation by Code Agent using Claude Sonnet 4.5.",
    type: "agent",
  },
  {
    name: "Deepseek V3",
    path: "/code-agent/deepseek-v3/",
    description: "Implementation by Code Agent using Deepseek V3.",
    type: "agent",
  },
  {
    name: "Qwen3 Coder Plus",
    path: "/code-agent/qwen3-coder-plus/",
    description: "Implementation by Code Agent using Qwen3 Coder Plus.",
    type: "agent",
  },
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 项目卡片组件
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

function ProjectCard({ project }: { project: Project }) {
  const tagClass =
    project.type === "baseline"
      ? "bg-gray-100 text-gray-700"
      : "bg-blue-50 text-blue-800";

  const tagLabel = project.type === "baseline" ? "Baseline" : "Code Agent";

  return (
    <a
      href={project.path}
      className="block h-full p-6 bg-white border border-gray-200 rounded-xl transition-all hover:-translate-y-1 hover:shadow-xl hover:border-gray-300"
    >
      <div className="flex items-center mb-4 text-sm">
        <span
          className={`px-3 py-1 rounded-full font-semibold uppercase tracking-wider text-xs ${tagClass}`}
        >
          {tagLabel}
        </span>
        <span className="ml-auto text-gray-500 font-mono text-xs">
          {project.path}
        </span>
      </div>
      <h2 className="mb-2 text-xl font-semibold text-blue-600">
        {project.name}
      </h2>
      <p className="text-gray-600 text-sm leading-relaxed">
        {project.description}
      </p>
    </a>
  );
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 主页组件
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

export default function Home() {
  return (
    <main className="max-w-4xl mx-auto px-8 py-12">
      <h1 className="text-3xl font-bold pb-4 mb-8 border-b-2 border-gray-200 text-gray-900">
        COMP7103 Project Examples
      </h1>

      <p className="mb-8 text-lg text-gray-600 leading-relaxed">
        A collection of arXiv CS Daily implementations demonstrating different
        development approaches.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {PROJECTS.map((project) => (
          <ProjectCard key={project.path} project={project} />
        ))}
      </div>
    </main>
  );
}
